module Dino
  module Components
    require 'dino/components/setup'
    require 'dino/components/mixins'
    require 'dino/components/basic'
    require 'dino/components/register'
    require 'dino/components/i2c'
    autoload :Led,              'dino/components/led'
    autoload :Button,           'dino/components/button'
    autoload :Sensor,           'dino/components/sensor'
    autoload :RGBLed,           'dino/components/rgb_led'
    autoload :Servo,            'dino/components/servo'
    autoload :SSD,              'dino/components/ssd'
    autoload :Stepper,          'dino/components/stepper'
    autoload :HD44780,          'dino/components/hd44780'
    autoload :Relay,            'dino/components/relay'
    autoload :SoftwareSerial,   'dino/components/software_serial'
    autoload :DHT,              'dino/components/dht'
    autoload :IREmitter,        'dino/components/ir_emitter'
    autoload :Piezo,            'dino/components/piezo'
    autoload :RotaryEncoder,    'dino/components/rotary_encoder'
    autoload :OneWire,          'dino/components/one_wire'
    autoload :Potentiometer,    'dino/components/potentiometer'
    autoload :L298,             'dino/components/l298'
  end
end
