name: Build / RP2040

on:
  workflow_dispatch:
  
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/build_rp2040.yml'

  push:
    paths:
      - 'src/**'
      - '.github/workflows/build_rp2040.yml'
      
jobs:
  rpipico:
    name: rp2040 ${{ matrix.sketches.name }}
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sketches:
          - name: serial
          - name: ethernet
          - name: wifi
            
        board:
          - fqbn: rp2040:rp2040:rpipicow
            dino-target: rp2040
            platforms: |
              - name: rp2040:rp2040
                source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
            libraries: |
              - name: Servo
              - name: LiquidCrystal
              - name: IRremote
                version: 4.0.0
              - name: Ethernet
              - name: WiFi
                
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate
        id: generate
        run: echo "path=$(./bin/dino sketch ${{ matrix.sketches.name }} --target ${{ matrix.board.dino-target }})" >> $GITHUB_OUTPUT

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.0.1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: |
            - ${{ steps.generate.outputs.path }}
            