name: Compile / ESP8266

on:
  workflow_dispatch:
  
  pull_request:
    paths:
      - 'src'
      - '.github/workflows/compile_esp8266.yml'

  push:
    paths:
      - 'src'
      - '.github/workflows/compile_esp8266.yml'
      
jobs:
  esp8266-nodemcuv2:
    name: esp8266 ${{ matrix.sketches.name }}
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sketches:
          - name: serial
          - name: wifi
            
        board:
          - fqbn: esp8266:esp8266:nodemcuv2
            dino-target: esp8266
            platforms: |
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            libraries: |
              - name: IRremoteESP8266
                version: 2.8.4

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate
        id: generate
        run: echo "path=$(./bin/dino sketch ${{ matrix.sketches.name }} --target ${{ matrix.board.dino-target }})" >> $GITHUB_OUTPUT

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.0.1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: |
            - ${{ steps.generate.outputs.path }}
            